server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mySuperSecretKeyForJwtToken123456
  expiration: 3600000